### ISSUE TITLE
Magnifier Icon not set correctly in search

### ISSUE THREAD

**Issue by CyRamos** [zcysxy/Obsidian-Terminal-Theme#15]
Hey 
Obsessed with your theme :) 
Could you only please fix the  icon of the magnifier? 🙏

![image](https://github.com/user-attachments/assets/3862a477-ae66-4b56-b723-cedd382ccd6c)

![image](https://github.com/user-attachments/assets/4aa4eeaa-958b-4e09-9984-e0cb22762ff0)

**Comment by krishpop** [comment]
+1 @zcysxy is there a fix for this? Do we just turn off icons

**Comment by Perseus333** [comment]
@krishpop @CyRamos 
I'm creating an updated version of this theme, private for the moment, and I fixed it by commenting out this lines:

 (line 1345 of theme.css)

```css
.document-replace > input[type='text']:focus,
.document-replace > input[type='text']:hover {
  border-width: 0;
  /* padding: 0 14px 1px 12px; */
  background-color: var(--background-primary);
  /* height: calc(var(--editor-line-height) * var(--the-font-size)); */
  /* margin: 0 8px; */
}
```
